server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          #uri: file:/home/rafa/Documentos/CursoSpringMicroservicios/Github
          uri: https://github.com/rafacampjurado/CursoMicroservicios.git
          default-label: main
